In [119]:
import numpy as np
n = 5
k = 3
I = np.eye(n)
F = np.random.randn(n, k)
d = np.random.randint(1, n, n)
D = np.diag(d)
Dinv = np.diag(1/d)
A = np.random.rand(k, k) + k * np.eye(k)
V = F.T@F
assert np.max(np.abs(D @ Dinv - I)) < 1e-14
V - V.T, np.linalg.eig(V), D

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 (array([9.11483979, 2.36854145, 3.69359883]),
  array([[-0.11392006,  0.75357915, -0.64741075],
         [-0.42055885,  0.55380766,  0.71862878],
         [-0.9000847 , -0.35414056, -0.25383458]])),
 array([[1, 0, 0, 0, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 3]]))

In [120]:
F @ V @ F.T

array([[ 20.01905909, -30.77034238,  -0.74027883,   1.82033924,
         10.02443334],
       [-30.77034238,  65.69390128,  -4.13115395,  -3.17922852,
         -7.22704878],
       [ -0.74027883,  -4.13115395,   3.51084158,  -2.85902807,
         -2.89298668],
       [  1.82033924,  -3.17922852,  -2.85902807,   4.43538873,
          1.00550986],
       [ 10.02443334,  -7.22704878,  -2.89298668,   1.00550986,
          8.67377459]])

In [121]:
FVFt = F @ V @ F.T
FVFtinv = F @ np.linalg.inv(V) @ F.T
FVFt @ FVFtinv

array([[ 20.01905909, -30.77034238,  -0.74027883,   1.82033924,
         10.02443334],
       [-30.77034238,  65.69390128,  -4.13115395,  -3.17922852,
         -7.22704878],
       [ -0.74027883,  -4.13115395,   3.51084158,  -2.85902807,
         -2.89298668],
       [  1.82033924,  -3.17922852,  -2.85902807,   4.43538873,
          1.00550986],
       [ 10.02443334,  -7.22704878,  -2.89298668,   1.00550986,
          8.67377459]])

In [113]:
Q = Dinv @ (I - FVFt @ np.linalg.inv(I + Dinv @ FVFt) @ Dinv)
Q @ (D + FVFt)

array([[ 1.00000000e+00,  3.22534194e-14, -2.71371160e-14,
        -1.45183482e-14,  1.55145035e-14],
       [ 3.89028828e-14,  1.00000000e+00, -4.08744531e-14,
        -2.11043543e-14,  2.37347019e-14],
       [-1.46848718e-14, -2.24750067e-14,  1.00000000e+00,
         9.92108219e-15, -1.27259426e-14],
       [-3.16773996e-15, -5.36685730e-15,  4.23734691e-15,
         1.00000000e+00, -3.07522181e-15],
       [ 5.01734286e-15,  7.71582883e-15, -6.54936696e-15,
        -3.11834206e-15,  1.00000000e+00]])

In [114]:
P = FVFt + D
np.linalg.cond(P)

65.89795799682074